### ISSUE TITLE
Using plugin in modular "Features"

### ISSUE THREAD

**Issue by mpetricek** [getgrav/grav-plugin-page-inject#11]
Hi there,

I'm trying to inject page to the default "Features" modular page from "Bootstrap" theme. I changed the textfield into editor in blueprints but it didn't help and the page is not injected in to the "Feature". Is it even suported to use injecting anywhere else than in content tab?

Thank you

**Comment by flaviocopes** [comment]
The plugin is only going to affect content inside the page, not in a page header. The features page stores its content in a page header property so it's not compatible.

**Comment by rhukster** [comment]
too old, closing
