### ISSUE TITLE
External Websites?

### ISSUE THREAD

**Issue by GillesC** [getgrav/grav-plugin-page-inject#12]
Hello

Is it possible to include external web pages, e.g., Github README pages?

Kind regards,
Gilles Callebaut

**Comment by rhukster** [comment]
This plugin is intended for "Grav Pages" only.  It lets you grab a page's content and drop it into another page.  It was never really intended to get arbitrary external pages that already have styling intended for an entire page.  I think it might be better to create another plugin that uses something like https://github.com/paquettg/php-html-parser to grab some specific content based on the remote DOM.
