### ISSUE TITLE
Asset pipeline for content-injected page processing

### ISSUE THREAD

**Issue by ScottHamper** [getgrav/grav-plugin-page-inject#15]
Hey All,

Coming up with a descriptive title for this is difficult, so here's my scenario:
- I've got a page that uses the [shortcode ui](https://github.com/getgrav/grav-plugin-shortcode-ui) plugin to insert a `ui-tabs` component.
- I have another page that content-injects the first page.

When viewing the second page, the `ui-tabs` shortcode appears to be processed - the final HTML output includes the appropriate markup. However, the relevant JS and CSS files for UI tabs are not added to the asset pipeline, and never make it onto the final page. As a result, the tabs component doesn't appear/function correctly.

Not sure if this is fundamentally an issue with the page-inject plugin or the shortcode-ui plugin, but figured I'd start here.

**Comment by rhukster** [comment]
The shortcode plugin uses an internal page storage meta mechanism to store any css/js the shortcode might need.  However, page-inject is not so smart.  You are losing the css/js when the contents of the shortcode is injected into a page and the output is cached as that page's content.  

There are some advancements to the way assets are handled coming in Grav 1.6.  When that happens, i plan on revisiting the shortcode core plugin as well as page-inject to see if we can make the assets more reliable when content is cached.

**Comment by ScottHamper** [comment]
Cool, sounds great! Thanks for the update

**Comment by rhukster** [comment]
too old, closing
