### ISSUE TITLE
Caching issue with Custom template

### ISSUE THREAD

**Issue by crusnac** [getgrav/grav-plugin-page-inject#16]
I am having an issue when using a custom template.  I am injecting a page using a custom template:

`[plugin:page-inject](/4.0/4.2/4.2.1/4.2.1.1?template=simple)`

The template is very simple:

````
<div class="standard-embed">
    <h3><a href="{{ page.url }}">{{ page.title }}</a></h3>
    {{ page.content }}
</div>
````

Everything is working as expected, with the exception of caching.  When I load the page that contains the injected pages, the simple template is rendered.  My challenge comes when I try to navigate to the /4.0/4.2/4.2.1/4.2.1.1 page, it loads the cached simple template? 

When caching is disabled, this behavior is not exhibited, so this leads me to believe that it's a caching issue.  Ideally, when injecting a page, it shouldn't write to the cache.

**Comment by rhukster** [comment]
Page inject will always cache the contents of your page, the page itself doesn't know that it should or should not be cached.  What happens if you disable caching on the page you are injecting stuff into explicitly with `cache_enable: false` ?

https://learn.getgrav.org/content/headers#cache-enable

**Comment by rhukster** [comment]
too old, closing
