### ISSUE TITLE
issue with cache enabled / pre-caching?

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-page-inject#2]
with system setting

```
cache:
  enabled: true
```

on pre-cached (?) pages the plugin-code

`[plugin:content-inject](/pathto/page)`

is not resolved but converted into:

`<a href="/pathto/page">plugin:content-inject</a>`

It works on the cache version of the current (opened in browser) page

**Comment by cord** [comment]
after tripple checking:

This issue is not related to advanced-pagecache

**Comment by rhukster** [comment]
Can't replicate. and this is quite old.
