### ISSUE TITLE
Inject non visible pages

### ISSUE THREAD

**Issue by rogeriocosta-mb** [getgrav/grav-plugin-page-inject#20]
Is it possible to page-inject plugin to when using something like ```[plugin:page-inject](/route/to/page)``` to respect the page published status on that route? I mean, I have on this route a page that is scheduled to be unpublished on a certain date (Page A), and another to go published on another date to replace that content (Page B).

So will the plugin follow the /route/to/page and get the latest content, in this case when the Page B goes live and the Page A is unpublished?

This would allow to set a specific route to serve content to another page (route), lets say a modular content that comes from that Page A or B according the route response thus preventing to have multiple modules to be scheduled there.

Is that possible?

**Comment by rhukster** [comment]
it will always try to get the page at the route requested.

**Comment by rogeriocosta-mb** [comment]
@rhukster First of all, thanks for answer :-) Ok, so if that route is a page that is non published it will load its content to inject anyway? Of it is a modular page with 3 modules, one of then is scheduled to be unpublished, lets say tomorrow, and when tomorrow arrives will it load all 3 or just the content of that route with those 2 active modules?

**Comment by rhukster** [comment]
it will pull published pages, so if the published status changes, then yes, the results might change.
