### ISSUE TITLE
Injecting files outside of user/pages

### ISSUE THREAD

**Issue by iagovar** [getgrav/grav-plugin-page-inject#21]
Hi, I'm trying to inject files outside of user/pages, particularly and html file that I need to include manually in some pages.

I'm currently using include($_SERVER["DOCUMENT_ROOT"] . "/activos/tabla-dating.html"); in my old custom-made CMS but I'm unable to do this with this plugin.

Is there any workaround?

**Comment by ricardo118** [comment]
use twig `{% include 'myhtmlfile.html' %}` dont need this plugin at all for that
