### ISSUE TITLE
Can't find page if the path to my page has a query string

### ISSUE THREAD

**Issue by gaatorre** [getgrav/grav-plugin-page-inject#23]
I noticed the find() function for pages fails to find the page due to the query string. Are there any workarounds?

**Comment by mahagr** [comment]
Pages cannot have query strings by themselves. I don't think there is a way to make it to work right now due to how query params are handled in the twig.

**Comment by rhukster** [comment]
The path does need to be a page route with nothing extra in the query string.  You should strip out the query string before using.  The only exception to this is `?template=` which is manually pulled out by the plugin if found.
