### ISSUE TITLE
Injected page not fully generated

### ISSUE THREAD

**Issue by awrog** [getgrav/grav-plugin-page-inject#25]
Occasionally the injected page is not fully generated. This can be easily reproduces.

Create test page to inject:
```
Text:  
* bullit 1
* bullit 2
   * subbullit 1.1
   * subbullit 1.2

Text continues..

```
inject with [plugin:content-inject](/test)

generates
![image](https://user-images.githubusercontent.com/12153667/95555335-e81f0180-0a11-11eb-8e23-aba6119da824.png)

**Comment by rhukster** [comment]
I can't replicate this, i always get the "Text continues.." text back

**Comment by awrog** [comment]
I try to use in a [RTFM Site](https://github.com/getgrav/grav-skeleton-rtfm-site)-based environment.
I guess [it](https://github.com/getgrav/grav-skeleton-rtfm-site) is heavily modified, or other plugins might be the culprit.
Too many factors to take into account, let's leave it.
