### ISSUE TITLE
Any interest in PR using shortcodes?

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-page-inject#26]
I've been playing around with this plugin and wondered why shortcodes aren't being used. Perhaps because shortcodes didn't exit back then?

Anyway, just for the fun of it, I've refactored it by using shortcodes. Is there any interest in that?

- To not break existing usage, I've added the shortcodes and kept existing regex based solution.
- I've also added the option to add a remote page.

If no interest, that's fine, it was out of curiosity...

**Comment by rhukster** [comment]
You are correct, short codes didn’t exist when this was created. A PR supporting both and defaulting to the standard way would be good.

**Comment by rhukster** [comment]
I actually did some refactoring and added a new 'remote' capability.  As part of this code rework, it made it much easier to add shortcodes, so i've done this now and updated the README with examples.  2.1.0 is what you will need.
