### ISSUE TITLE
issue with cache enabled / pre-caching Not Resoved

### ISSUE THREAD

**Issue by chellige** [getgrav/grav-plugin-page-inject#4]
Was there a fix for this issue. I am experiencing the same problem where the code is converted into a hyperlink. Seems to be an issue if caching is enabled or disabled.

`[plugin:content-inject](/pathto/page)`

is not resolved but converted into:

`<a href="/pathto/page">plugin:content-inject</a>`

**Comment by paulhibbitts** [comment]
I seem to be getting this now too, but I am not sure why. Using Grav 1.10 and the rendered HTML code from the plugin in Markdown is:
`<p><a href="/example-grav-skeleton-course-hub-site/sidebar">plugin:content-inject</a></p>`

With Markdown code of:
`[plugin:content-inject](../sidebar)`

Any ideas?

**Comment by rhukster** [comment]
Page inject is working for me with caching on, although I do have it enabled in the page header:

```
page-inject:
    active: true
    processed_content: true
```

Some examples i'm using:

```
This is a test of Page Inject plugin:

[plugin:content-inject](/media)

[plugin:page-inject](/test/modular/_callout)

[plugin:page-inject](/test/parsedown?template=page-inject)
```

**Comment by rhukster** [comment]
I think that **page-inject** plugin is not running, it's merely processing as a regular markdown link.

**Comment by rhukster** [comment]
Ok, that's the problem.  It's not merging the data with the defaults properly.  If you set those `page-inject` options on the page it works fine.  Else it's not falling back.. I'l sort this out.. in the meantime, page-level overrides make it work.

**Comment by rhukster** [comment]
Thought i had something, but no, had a configuration override setting `active: false` globally, so working as expected.  Caching works for me too.

**Comment by paulhibbitts** [comment]
Thanks for taking a look. Still no luck, cache is off and plugin settings are:

`enabled: true
active: true
processed_content: true
`

And also tried the page header:

`````` ---
title: 'Syllabus'
page-inject:
    active: true
    processed_content: true
---

[plugin:content-inject](../sidebar)```

Stumped, am I still missing something here?
``````

**Comment by rhukster** [comment]
can you paste that between triple backticks? i can't make sense of it all on one line :)

**Comment by rhukster** [comment]
It could be a conflict with some other plugin i suppose.. can you turn on the debugger, and check the 'plugins' tab and make sure **page-inject** is configured enabled and active there:

![plugins grav 2016-05-26 22-18-06](https://cloud.githubusercontent.com/assets/1084697/15597686/c4aaf73a-238f-11e6-873f-b481bea58f37.png)

**Comment by paulhibbitts** [comment]
Thanks, confirmed it is running via Debug. Will try to determine possible plugin conflicts tomorrow and get back to you.

**Comment by paulhibbitts** [comment]
Just tried a quick test of disabling all other plugins but still no luck. Will do more testing tomorrow.

**Comment by paulhibbitts** [comment]
Ok, I think I've identified the issue. The path used for the page-inject plugin seems to be less 'forgiving' than the path route used to link to the same page.

For example, with all pages at the root (each within their own folder) the link to the page 'test'  from another page at the same level could be either:

```
[Test](../test)
```

Or

```
[Test](/test)
```

However, for the page-inject plugin to render a page the path format needs to be in this format:

```
[plugin:content-inject](/test)
```

Whenever the page is deemed not 'available' in the page-inject plugin the behavior is to present the entire command as a hyperlink, which is what I was seeing.

So, does the page-inject plugin **require** absolute links? If so, I could try to highlight that issue in the ReadMe if you would like.

Thanks,
Paul

**Comment by rhukster** [comment]
Yes currently it requires a 'route' it does not support any path calculations like markdown links. It may be possible to improve this plugin with link calculation.  Maybe create a new issue for that feature request.
