### ISSUE TITLE
Support for page path calculations

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-plugin-page-inject#5]
As discussed in #2 , page-inject currently only support absolute page paths. It would be a nice enhancement (and likely reduce user errors) to also support calculated page paths like the ones supported in Markdown (i.e. ../page/path).

Thanks very much for considering this request.
Paul

**Comment by rhukster** [comment]
Fixed in next release

**Comment by rhukster** [comment]
and released!

**Comment by paulhibbitts** [comment]
Awesome, thanks so much Andy!
