### ISSUE TITLE
Header duplication when using a template

### ISSUE THREAD

**Issue by crusnac** [getgrav/grav-plugin-page-inject#7]
Headers are duplicated when specifying a template.   It appears that the the page-inject plugin is double parsing the headers.

Control template: 

`<div class="control">
    <h2>{{header.variable1}}</h2>
    {% block control %}{{page.content}}{% endblock %}
</div>`

Content & Output Details:

![screen shot 2016-10-10 at 2 41 02 pm](https://cloud.githubusercontent.com/assets/5386135/19276270/b8061c1e-8f8a-11e6-9e5c-2cef02d3fbbe.png)

![screen shot 2016-10-10 at 2 31 12 pm](https://cloud.githubusercontent.com/assets/5386135/19276287/c0b6540a-8f8a-11e6-892f-778846c80479.png)

HTML output:

`<div class="control">
    <h2 id="inject-me">inject me<a class="anchorjs-link " href="#inject-me" aria-label="Anchor link for: inject me" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant-ligatures: normal; font-variant-position: normal; font-variant-caps: normal; font-variant-numeric: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h2>
    <div class="control">
    <h2 id="inject-me-1">inject me<a class="anchorjs-link " href="#inject-me-1" aria-label="Anchor link for: inject me 1" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant-ligatures: normal; font-variant-position: normal; font-variant-caps: normal; font-variant-numeric: normal; font-variant-alternates: normal; font-variant-east-asian: normal; font-weight: normal; line-height: 1; padding-left: 0.375em;"></a></h2>
    <p>Labeling is the practice of marking a system or document with its appropriate sensitivity level so that others know how to appropriately handle the information. Information that can be printed (e.g., spreadsheets, files, reports, drawings, or handouts) must contain one of the following confidentiality symbols in the document footer on every printed page (see below), or simply the words if the graphic is not technically feasible. The exception for labeling is with marketing material, since marketing material is primarily developed for public release. Restricted or Confidential information that is displayed or viewed (e.g., websites, presentations, etc.) must be labeled with its classification as part of the display.  </p></div></div>`

**Comment by rhukster** [comment]
Fixed in next release.

**Comment by rhukster** [comment]
and released!
