### ISSUE TITLE
Not replacing by content (multilanguage)

### ISSUE THREAD

**Issue by risoul** [getgrav/grav-plugin-page-inject#9]
I use grav landio skeleton and multilanguage
I created a test page (en) and the test2 page (en) with the plugin snippet.
I just get a link to the test page, the content is not injected. Tried /en/test or /test without success.

**Comment by risoul** [comment]
I can confirm after testing from a fresh install, that all works fine before enabling multilanguage (with browser detection) but fail after enabling multilanguage.

**Comment by ArrowBaZ** [comment]
same issue here
How can I help form debug ?

**Comment by Bokelmann** [comment]
This is still not working ... I have Version 1.2.0 of this awesome plugin. But it does not work when I enable the Include default language. @rhukster I hope this can be fixed soon?
